### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by simontegg** [smallhelm/level-fact-base#3]
Very cool library! 
I just have a few questions if you don't mind:
1. Can you point me to where in the source the join magic happens?
2. The examples show equality-based queries. Are there plans to support other operators  like `>` `<` etc?

**Comment by farskipper** [comment]
1. [src/q.js line 200-214](https://github.com/smallhelm/level-fact-base/blob/b48fc5884677470b7bf9146e2ba4216c0216661f/src/q.js#L200-L214)
The `memo` is the bindings of variables to values. It searches the first tuple using the initial bindings, then the next tuple using the bindings found in the previous tuple and so forth. Hope that made sense.

2. Not currently, but I'm not opposed to adding that. Datomic also allows one to pass in an arbitrary function that filters a value which would also be cool.

**Comment by simontegg** [comment]
Thanks.  I'll have a poke around. Passing in an arbitrary filter would be a good API
